# Data Curation

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd

## Load Dataset

In [27]:
df=pd.read_csv("../data/input/IC50LibA.csv")
df

,ID,Smile,IC50(nM)
0,C33H44N6O11,CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CNC(=O...,3.4
1,C32H44N6O9,CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CNC(=O...,16.0
2,C41H64N8O14,CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](N...,0.6
3,C43H66N8O14,CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](N...,16.0
4,C34H63N5O6S,CCCCNC(=O)[C@@H](NC(=O)[C@@H]1CCC[C@H]1[C@H](O...,25.0
...,...,...,...
175,234860,CO[C@H]1CC[C@@]2(Cc3ccc(OCC(F)(F)F)cc3C22N=C(N...,25.0
176,234917,COC1CCC2(Cc3ccc(cc3C22ON(C)C(N)=N2)-c2cccc(c2)...,26.2
177,234819,CO[C@H]1CC[C@@]2(Cc3ccc(CCC(C)C)cc3C22N=C(N)N(...,27.1
178,234814,CCCCCc1ccc2C[C@@]3(CC[C@@H](CC3)OC)C3(ON(C)C(N...,29.8
179,234901,CO[C@H]1CC[C@@]2(Cc3ccc(OCC4CCCO4)cc3C22N=C(N)...,31.0

## Dataset Overview

In [28]:
df.columns

Index(['ID', 'Smile', 'IC50(nM)'], dtype='str')

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        180 non-null    str
 1   Smile     180 non-null    str
 2   IC50(nM)  180 non-null    float64
dtypes: float64(1), str(2)
memory usage: 4.3 KB

## Check Duplicate Ligands

In [30]:
duplicate=df[df.duplicated(subset='Smile',keep= False)]
duplicate

,ID,Smile,IC50(nM)
2,C41H64N8O14,CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](N...,0.6
44,CHEMBL78946,CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](N...,1.6
49,CHEMBL6049095,CN1C(N)=N[C@](C)(c2cc(/C=C(\F)c3cnc(Cl)cn3)ccc...,3.0
64,CHEMBL6049096,CN1C(N)=N[C@](C)(c2cc(/C=C(\F)c3cnc(Cl)cn3)ccc...,6.0
155,234836,CO[C@H]1CC[C@@]2(Cc3ccc(CCC(C)C)cc3C22N=C(N)N(...,10.0
165,234822,CO[C@H]1CC[C@@]2(Cc3ccc(CCC(C)C)cc3C22N=C(N)N(...,15.8

## Remove Duplicate Ligands

Duplicate molecules were identified based on SMILES strings
When duplicate SMILES existed, the median IC50 value was retained.

In [31]:
df= df.groupby("Smile", as_index=False).agg({'ID':'first', 'IC50(nM)': 'median'})
df

,Smile,ID,IC50(nM)
0,C#CCOc1cnc(/C(F)=C/c2ccc(F)c([C@]3(C)CS(=O)(=O...,CHEMBL6010325,3.00
1,C#CCOc1cnc(/C(F)=C/c2ccc(F)c([C@]34CN(C(=O)OC(...,CHEMBL5905447,2.62
2,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(-...,C27H18FN5O2,0.43
3,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(C...,C27H22N4O3,0.46
4,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(C...,C27H22N4O3,0.31
...,...,...,...
172,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C23H18ClN5O3,3.60
173,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C25H22ClN5O4,0.57
174,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C20H13Cl2N5O3,21.00
175,NC1=N[C@@]2(c3cc(-c4cccnc4F)ccc3Oc3c(F)cc([N+]...,CHEMBL4109073,0.60
176,NC1=N[C@@]2(c3cc(NC(=O)c4ccc(F)cn4)ccc3F)COC[C...,CHEMBL3672941,15.60

In [32]:
print(f"Initial molecules : 180")
print(f"After curation    : {len(df)}")

Initial molecules : 180
After curation    : 177

## Calculate pIC50
The IC50 values (nM) were converted to pIC50 using

pIC50 = -log10(IC50 × 10⁻⁹)

In [33]:
df['pIC50']=-np.log10(df['IC50(nM)']*1e-9)
df

,Smile,ID,IC50(nM),pIC50
0,C#CCOc1cnc(/C(F)=C/c2ccc(F)c([C@]3(C)CS(=O)(=O...,CHEMBL6010325,3.00,8.522879
1,C#CCOc1cnc(/C(F)=C/c2ccc(F)c([C@]34CN(C(=O)OC(...,CHEMBL5905447,2.62,8.581699
2,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(-...,C27H18FN5O2,0.43,9.366532
3,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(C...,C27H22N4O3,0.46,9.337242
4,CC#Cc1cncc(-c2ccc3c(c2)[C@@]2(COC(N)=N2)c2cc(C...,C27H22N4O3,0.31,9.508638
...,...,...,...,...
172,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C23H18ClN5O3,3.60,8.443697
173,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C25H22ClN5O4,0.57,9.244125
174,NC1=N[C@@]2(CO1)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1Oc...,C20H13Cl2N5O3,21.00,7.677781
175,NC1=N[C@@]2(c3cc(-c4cccnc4F)ccc3Oc3c(F)cc([N+]...,CHEMBL4109073,0.60,9.221849
176,NC1=N[C@@]2(c3cc(NC(=O)c4ccc(F)cn4)ccc3F)COC[C...,CHEMBL3672941,15.60,7.806875

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Smile     177 non-null    str
 1   ID        177 non-null    str
 2   IC50(nM)  177 non-null    float64
 3   pIC50     177 non-null    float64
dtypes: float64(2), str(2)
memory usage: 5.7 KB

## Save Curated Dataset

In [35]:
df.to_csv("../data/output/pIC50LibA.csv",  index=False)